name: CI Showcase

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install dependencies for Selenium and API tests
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Pull Docker image for emulator (this includes Android SDK)
      - name: Pull Docker image for emulator
        run: |
          docker pull noxqa/docker-showcase:v1.0

      # Run Docker container with Emulator (for Appium tests)
      - name: Run Docker container with Emulator
        run: |
          docker run -d --name android-emulator --privileged noxqa/docker-showcase:v1.0

      # Wait for Emulator to Boot
      - name: Wait for Emulator to Boot
        run: |
          TIMEOUT=300  # 5-minute timeout for the emulator to boot
          COUNTER=0
          while ! docker exec android-emulator adb devices | grep -q "emulator"; do
            if [ $COUNTER -ge $TIMEOUT ]; then
              echo "Emulator did not start in time!"
              exit 1
            fi
            sleep 5
            COUNTER=$((COUNTER+1))
            echo "Waiting for emulator to boot... ($COUNTER)"
          done
          docker exec android-emulator adb shell input keyevent 82  # Unlock the emulator

      # Run Appium tests inside the Docker container (for the emulator)
      - name: Run Appium tests
        run: |
          docker exec android-emulator pytest /workspace/appium_tests/ --maxfail=0 --disable-warnings -v

      # Run API tests (directly in GitHub Actions environment)
      - name: Run API tests
        run: |
          pytest api_tests/ --maxfail=0 --disable-warnings -v

      # Run Selenium tests (directly in GitHub Actions environment)
      - name: Run Selenium tests
        run: |
          pytest selenium_tests/ --maxfail=0 --disable-warnings -v

      # Upload logs if tests fail
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: ./logs
