name: CI Showcase

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      appium:
        image: appium/appium
        options: >-
          --publish 4723:4723

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          java-version: 11

      - name: Install system images for emulator
        run: |
          sdkmanager "system-images;android-30;google_apis;x86_64"

      - name: Update Emulator and SDK Packages
        run: |
          sdkmanager --update
          sdkmanager --install "emulator" "platform-tools" "platforms;android-30" "build-tools;30.0.3"

      - name: Create AVD
        run: |
          # Create AVD with appropriate settings
          echo "no" | avdmanager create avd --force --name test --package 'system-images;android-30;google_apis;x86_64' --device "pixel_4a" --sdcard 512M

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel_4a
          emulator-options: "-no-window -no-boot-anim -writable-system"
          script: |
            # Wait for the emulator to start
            adb devices
            adb wait-for-device
            adb shell input keyevent 82 # Unlock the emulator

      - name: Wait for Emulator to Boot
        run: |
          # Ensure the emulator is fully booted
          adb wait-for-device
          adb shell input keyevent 82  # Unlock the emulator

      - name: Ensure logs directory exists
        run: |
          mkdir -p ./logs
          chmod -R 777 ./logs

      - name: Run Selenium tests
        run: |
          pytest selenium_tests/ --maxfail=0 --disable-warnings -v

      - name: Run API tests
        run: |
          pytest api_tests/ --maxfail=0 --disable-warnings -v

      - name: Run Appium tests
        run: |
          pytest appium_tests/ --maxfail=0 --disable-warnings -v

      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: ./logs
