name: CI Showcase

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Run API tests with Allure
        run: |
          pytest api_tests/ --maxfail=0 --disable-warnings -v --alluredir=allure-results/api

      - name: Run Selenium tests with Allure
        run: |
          pytest selenium_tests/ --maxfail=0 --disable-warnings -v --alluredir=allure-results/selenium

      - name: Upload Allure results for API tests
        if: always()  # Ensure this step runs even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: allure-results-api
          path: allure-results/api

      - name: Upload Allure results for Selenium tests
        if: always()  # Ensure this step runs even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: allure-results-selenium
          path: allure-results/selenium

      - name: Upload logs
        if: failure()  # Upload logs only if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: ./logs
