name: CI Showcase

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure logs directory exists
        run: |
          mkdir -p ./logs  # Ensure the logs directory exists
          chmod -R 777 ./logs  # Grant full read/write/execute permissions to the logs folder

      - name: Run Selenium tests
        run: |
          pytest selenium_tests/ --maxfail=0 --disable-warnings -v
        continue-on-error: true

      - name: Run API tests
        run: |
          pytest api_tests/ --maxfail=0 --disable-warnings -v

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: ./logs
